name = "MRINavigator"
uuid = "eacce8a8-16e1-4f0a-a125-bfe7a196bd66"
authors = ["Laura Beghini"]
version = "0.1.0"

[deps]
MRICoilSensitivities = "c57eb701-aafc-44a2-a53c-128049758959"
MRIReco = "bdf86e05-2d2b-5731-a332-f3fe1f9e047f"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
