name = "MRINavigator"
uuid = "eacce8a8-16e1-4f0a-a125-bfe7a196bd66"
authors = ["Laura Beghini"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
